<select class="block text-sm text-gray-600 w-full px-5 py-2 outline-none border" name="name" required>
                        <option value="" class="w-full text-gray-700 bg-gray-200 border rounded">Select Drug</option>
                        <!-- Example Drugs, you can replace or expand this list -->
                        <option value="Paracetamol" class="w-full text-gray-700 bg-gray-200 rounded">Paracetamol</option>
                        <option value="Zubes" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Zubes</option>
                        <option value="Ibuprofen" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Ibuprofen</option>
                        <option value="Amoxicillin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Amoxicillin</option>
                        <option value="Metformin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Metformin</option>
                        <option value="Aspirin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Aspirin</option>
                        <option value="Cetirizine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Cetirizine</option>
                        <option value="Simvastatin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Simvastatin</option>
                        <option value="Lisinopril" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Lisinopril</option>
                        <option value="Omeprazole" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Omeprazole</option>
                        <option value="Lorazepam" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Lorazepam</option>
                        <option value="Doxycycline" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Doxycycline</option>
                        <option value="Furosemide" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Furosemide</option>
                        <option value="Hydrochlorothiazide" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Hydrochlorothiazide</option>
                        <option value="Metoprolol" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Metoprolol</option>
                        <option value="Prednisone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Prednisone</option>
                        <option value="Albuterol" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Albuterol</option>
                        <option value="Gabapentin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Gabapentin</option>
                        <option value="Amlodipine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Amlodipine</option>
                        <option value="Diazepam" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Diazepam</option>
                        <option value="Atorvastatin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Atorvastatin</option>
                        <option value="Clonazepam" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Clonazepam</option>
                        <option value="Naproxen" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Naproxen</option>
                        <option value="Levothyroxine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Levothyroxine</option>
                        <option value="Venlafaxine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Venlafaxine</option>
                        <option value="Tramadol" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Tramadol</option>
                        <option value="Ranitidine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Ranitidine</option>
                        <option value="Ciprofloxacin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Ciprofloxacin</option>
                        <option value="Insulin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Insulin</option>
                        <option value="Loratadine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Loratadine</option>
                        <option value="Atenolol" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Atenolol</option>
                        <option value="Buspirone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Buspirone</option>
                        <option value="Enalapril" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Enalapril</option>
                        <option value="Sildenafil" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Sildenafil</option>
                        <option value="Duloxetine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Duloxetine</option>
                        <option value="Fexofenadine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Fexofenadine</option>
                        <option value="Methylprednisolone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Methylprednisolone</option>
                        <option value="Methotrexate" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Methotrexate</option>
                        <option value="Phenobarbital" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Phenobarbital</option>
                        <option value="Hydrocodone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Hydrocodone</option>
                        <option value="Codeine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Codeine</option>
                        <option value="Nitroglycerin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Nitroglycerin</option>
                        <option value="Lorazepam" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Lorazepam</option>
                        <option value="Bupropion" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Bupropion</option>
                        <option value="Oxytocin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Oxytocin</option>
                        <option value="Risperidone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Risperidone</option>
                        <option value="Topiramate" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Topiramate</option>
                        <option value="Ezetimibe" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Ezetimibe</option>
                        <option value="Hydroxychloroquine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Hydroxychloroquine</option>
                        <option value="Methadone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Methadone</option>
                        <option value="Ropinirole" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Ropinirole</option>
                        <option value="Divalproex" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Divalproex</option>
                        <option value="Buspirone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Buspirone</option>
                        <option value="Quetiapine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Quetiapine</option>
                        <option value="Acarbose" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Acarbose</option>
                        <option value="Mirtazapine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Mirtazapine</option>
                        <option value="Pramipexole" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Pramipexole</option>
                        <option value="Loxapine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Loxapine</option>
                        <option value="Vilazodone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Vilazodone</option>
                        <option value="Apixaban" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Apixaban</option>
                        <option value="Clopidogrel" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Clopidogrel</option>
                        <option value="Tamsulosin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Tamsulosin</option>
                        <option value="Propranolol" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Propranolol</option>
                        <option value="Spironolactone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Spironolactone</option>
                        <option value="Digoxin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Digoxin</option>
                        <option value="Dabigatran" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Dabigatran</option>
                        <option value="Fluconazole" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Fluconazole</option>
                        <option value="Trazodone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Trazodone</option>
                        <option value="Hydroxyzine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Hydroxyzine</option>
                        <option value="Lamotrigine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Lamotrigine</option>
                        <option value="Telmisartan" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Telmisartan</option>
                        <option value="Pregabalin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Pregabalin</option>
                        <option value="Epinephrine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Epinephrine</option>
                        <option value="Baclofen" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Baclofen</option>
                        <option value="Candesartan" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Candesartan</option>
                        <option value="Oxycodone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Oxycodone</option>
                        <option value="Ceftriaxone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Ceftriaxone</option>
                        <option value="Doxylamine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Doxylamine</option>
                        <option value="Fentanyl" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Fentanyl</option>
                        <option value="Valacyclovir" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Valacyclovir</option>
                        <option value="Diphenhydramine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Diphenhydramine</option>
                        <option value="Rifampin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Rifampin</option>
                        <option value="Azithromycin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Azithromycin</option>
                        <option value="Topiramate" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Topiramate</option>
                        <option value="Propranolol" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Propranolol</option>
                        <option value="Mupirocin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Mupirocin</option>
                        <option value="Hydralazine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Hydralazine</option>
                        <option value="Acyclovir" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Acyclovir</option>
                        <option value="Ethambutol" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Ethambutol</option>
                        <option value="Chlorpromazine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Chlorpromazine</option>
                        <option value="Gabapentin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Gabapentin</option>
                        <option value="Clarithromycin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Clarithromycin</option>
                        <option value="Loratadine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Loratadine</option>
                        <option value="Omeprazole" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Omeprazole</option>
                        <option value="Ranitidine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Ranitidine</option>
                        <option value="Diclofenac" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Diclofenac</option>
                        <option value="Lansoprazole" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Lansoprazole</option>
                        <option value="Terazosin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Terazosin</option>
                        <option value="Doxazosin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Doxazosin</option>
                        <option value="Bupropion" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Bupropion</option>
                        <option value="Amiodarone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Amiodarone</option>
                        <option value="Levetiracetam" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Levetiracetam</option>
                        <option value="Memantine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Memantine</option>
                        <option value="Milnacipran" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Milnacipran</option>
                        <option value="Naltrexone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Naltrexone</option>
                        <option value="Nifedipine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Nifedipine</option>
                        <option value="Valproic Acid" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Valproic Acid</option>
                        <option value="Nabumetone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Nabumetone</option>
                        <option value="Meclizine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Meclizine</option>
                        <option value="Oxybutynin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Oxybutynin</option>
                        <option value="Saxagliptin" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Saxagliptin</option>
                        <option value="Sildenafil" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Sildenafil</option>
                        <option value="Prednisone" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Prednisone</option>
                        <option value="Chloroquine" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Chloroquine</option>
                        <option value="Citalopram" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Citalopram</option>
                        <option value="Lorazepam" class="w-full outline-none text-gray-700 bg-gray-200 rounded">Lorazepam</option>
                    </select>