
<select name="illness" class="block w-full px-5 py-2 text-sm text-gray-600 border outline-none rounded" required>
    <option value="" disabled selected>Select Illness</option>
    <option value="Headache">Headache</option>
    <option value="Fever">Fever</option>
    <option value="Cough">Cough</option>
    <option value="Pain Relief">Pain Relief</option>
    <option value="Cold">Cold</option>
    <option value="Inflammation">Inflammation</option>
    <option value="Asthma">Asthma</option>
    <option value="Allergy">Allergy</option>
    <option value="High Blood Pressure">High Blood Pressure</option>
    <option value="Diabetes">Diabetes</option>
    <option value="Cholesterol Control">Cholesterol Control</option>
    <option value="Heart Disease">Heart Disease</option>
    <option value="Infection">Infection</option>
    <option value="Acid Reflux">Acid Reflux</option>
    <option value="Ulcers">Ulcers</option>
    <option value="Anxiety">Anxiety</option>
    <option value="Depression">Depression</option>
    <option value="Insomnia">Insomnia</option>
    <option value="Osteoporosis">Osteoporosis</option>
    <option value="Arthritis">Arthritis</option>
    <option value="Seizures">Seizures</option>
    <option value="Thyroid Disorders">Thyroid Disorders</option>
    <option value="Viral Infection">Viral Infection</option>
    <option value="Fungal Infection">Fungal Infection</option>
    <option value="Bacterial Infection">Bacterial Infection</option>
    <option value="Parasite Infection">Parasite Infection</option>
    <option value="Skin Conditions">Skin Conditions</option>
    <option value="Psoriasis">Psoriasis</option>
    <option value="Acne">Acne</option>
    <option value="Eczema">Eczema</option>
    <option value="Rheumatism">Rheumatism</option>
    <option value="Gout">Gout</option>
    <option value="Menstrual Pain">Menstrual Pain</option>
    <option value="Birth Control">Birth Control</option>
    <option value="Pregnancy">Pregnancy</option>
    <option value="Postpartum Depression">Postpartum Depression</option>
    <option value="Impotence">Impotence</option>
    <option value="Prostate Conditions">Prostate Conditions</option>
    <option value="Urinary Tract Infection">Urinary Tract Infection</option>
    <option value="Kidney Disease">Kidney Disease</option>
    <option value="Liver Disease">Liver Disease</option>
    <option value="Eye Infection">Eye Infection</option>
    <option value="Ear Infection">Ear Infection</option>
    <option value="Sinus Infection">Sinus Infection</option>
    <option value="Bronchitis">Bronchitis</option>
    <option value="Pneumonia">Pneumonia</option>
    <option value="Tuberculosis">Tuberculosis</option>
    <option value="HIV/AIDS">HIV/AIDS</option>
    <option value="Hepatitis">Hepatitis</option>
    <option value="Herpes">Herpes</option>
    <option value="Shingles">Shingles</option>
    <option value="Chickenpox">Chickenpox</option>
    <option value="Measles">Measles</option>
    <option value="Mumps">Mumps</option>
    <option value="Rubella">Rubella</option>
    <option value="COVID-19">COVID-19</option>
    <option value="Cancer">Cancer</option>
    <option value="Tumor">Tumor</option>
    <option value="Lymphoma">Lymphoma</option>
    <option value="Leukemia">Leukemia</option>
    <option value="Migraine">Migraine</option>
    <option value="Stroke">Stroke</option>
    <option value="Epilepsy">Epilepsy</option>
    <option value="Multiple Sclerosis">Multiple Sclerosis</option>
    <option value="Parkinson's Disease">Parkinson's Disease</option>
    <option value="Alzheimer's Disease">Alzheimer's Disease</option>
    <option value="Dementia">Dementia</option>
    <option value="ALS (Lou Gehrig's Disease)">ALS (Lou Gehrig's Disease)</option>
    <option value="Huntington's Disease">Huntington's Disease</option>
    <option value="Crohn's Disease">Crohn's Disease</option>
    <option value="Colitis">Colitis</option>
    <option value="Irritable Bowel Syndrome (IBS)">Irritable Bowel Syndrome (IBS)</option>
    <option value="Constipation">Constipation</option>
    <option value="Diarrhea">Diarrhea</option>
    <option value="Hemorrhoids">Hemorrhoids</option>
    <option value="Gallbladder Disease">Gallbladder Disease</option>
    <option value="Pancreatitis">Pancreatitis</option>
    <option value="Anemia">Anemia</option>
    <option value="Sickle Cell Disease">Sickle Cell Disease</option>
    <option value="Hemophilia">Hemophilia</option>
    <option value="Leukocytosis">Leukocytosis</option>
    <option value="Thrombocytopenia">Thrombocytopenia</option>
    <option value="Lupus">Lupus</option>
    <option value="Fibromyalgia">Fibromyalgia</option>
    <option value="Chronic Fatigue Syndrome">Chronic Fatigue Syndrome</option>
    <option value="Obesity">Obesity</option>
    <option value="Malnutrition">Malnutrition</option>
    <option value="Eating Disorders">Eating Disorders</option>
    <option value="Substance Abuse">Substance Abuse</option>
    <option value="Alcoholism">Alcoholism</option>
    <option value="Smoking Cessation">Smoking Cessation</option>
    <option value="Detoxification">Detoxification</option>
</select>